"""
Contains all string literals for PDU types, phases, error codes, etc.
"""

# Store string literals of PDU types here for convenience
class PDU:
    # C->S
    PLAYER_READY = "PLAYER_READY"
    MULLIGAN_CHOICE = "MULLIGAN_CHOICE"
    PRIORITY_PASS = "PRIORITY_PASS"
    CAST_SPELL = "CAST_SPELL"
    ACTIVATE_ABILITY = "ACTIVATE_ABILITY"
    PLAY_LAND = "PLAY_LAND"
    DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
    DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
    ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
    TRIGGER_ORDER_RESPONSE = "TRIGGER_ORDER_RESPONSE"
    TRIGGER_CHOICE_RESPONSE = "TRIGGER_CHOICE_RESPONSE"
    DISCARD = "DISCARD"
    CONCEDE = "CONCEDE"
    PING = "PING"

    # S->C(P1/P2)/ALL
    GAME_STATE_UPDATE = "GAME_STATE_UPDATE"
    PHASE_TRANSITION = "PHASE_TRANSITION"
    PRIORITY_GRANT = "PRIORITY_GRANT"
    STACK_PUSH = "STACK_PUSH"
    STACK_RESOLVE = "STACK_RESOLVE"
    TRIGGER_ORDER = "TRIGGER_ORDER"
    TRIGGER_CHOICE = "TRIGGER_CHOICE"
    COMBAT_DAMAGE_RESULT = "COMBAT_DAMAGE_RESULT"
    GAME_OVER = "GAME_OVER"
    ERROR = "ERROR"
    PONG = "PONG"

# Global variables
DEFAULT_PORT = 4444
#STARTING_LIFE =
#MAX_HAND_SIZE =
#MAX_DECK_SIZE =
#MIN_DECK_SIZE =
#DEFAULT_TIME_LIMIT =
#PING_INTERVAL =
#PING_TIMEOUT =