"""
Contains all string literals for PDU types, phases, error codes, etc.
"""

# Game lifecycle phases for phase transition
class Phase:
    LOBBY = "LOBBY"
    MULLIGAN = "MULLIGAN"
    UNTAP = "UNTAP"
    UPKEEP = "UPKEEP"
    DRAW = "DRAW"
    PRECOMBAT_MAIN = "PRECOMBAT_MAIN"
    BEGIN_COMBAT = "BEGIN_COMBAT"
    DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
    DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
    ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
    FIRST_STRIKE_DAMAGE = "FIRST_STRIKE_DAMAGE"
    COMBAT_DAMAGE = "COMBAT_DAMAGE"
    END_OF_COMBAT = "END_OF_COMBAT"
    POSTCOMBAT_MAIN = "POSTCOMBAT_MAIN"
    END_STEP = "END_STEP"
    CLEANUP = "CLEANUP"
    GAME_OVER = "GAME_OVER"

# Turn phase order (used by turn_manager)
PHASE_ORDER = [
    Phase.UNTAP,
    Phase.UPKEEP,
    Phase.DRAW,
    Phase.PRECOMBAT_MAIN,
    Phase.BEGIN_COMBAT,
    Phase.DECLARE_ATTACKERS,
    Phase.DECLARE_BLOCKERS,
    Phase.ASSIGN_DAMAGE_ORDER,
    Phase.COMBAT_DAMAGE,
    Phase.END_OF_COMBAT,
    Phase.POSTCOMBAT_MAIN,
    Phase.END_STEP,
    Phase.CLEANUP
]

# Store string literals of PDU types here for convenience
class PDU:
    # C->S
    PLAYER_READY = "PLAYER_READY"
    MULLIGAN_CHOICE = "MULLIGAN_CHOICE"
    PRIORITY_PASS = "PRIORITY_PASS"
    CAST_SPELL = "CAST_SPELL"
    ACTIVATE_ABILITY = "ACTIVATE_ABILITY"
    PLAY_LAND = "PLAY_LAND"
    DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
    DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
    ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
    TRIGGER_ORDER_RESPONSE = "TRIGGER_ORDER_RESPONSE"
    TRIGGER_CHOICE_RESPONSE = "TRIGGER_CHOICE_RESPONSE"
    DISCARD = "DISCARD"
    CONCEDE = "CONCEDE"
    PING = "PING"

    # S->C(P1/P2)/ALL
    GAME_STATE_UPDATE = "GAME_STATE_UPDATE"
    PHASE_TRANSITION = "PHASE_TRANSITION"
    PRIORITY_GRANT = "PRIORITY_GRANT"
    STACK_PUSH = "STACK_PUSH"
    STACK_RESOLVE = "STACK_RESOLVE"
    TRIGGER_ORDER = "TRIGGER_ORDER"
    TRIGGER_CHOICE = "TRIGGER_CHOICE"
    COMBAT_DAMAGE_RESULT = "COMBAT_DAMAGE_RESULT"
    GAME_OVER = "GAME_OVER"
    ERROR = "ERROR"
    PONG = "PONG"

# Error codes for ERROR PDUs
class ErrorCode:
    INVALID_JSON = "INVALID_JSON"
    ILLEGAL_DECK = "ILLEGAL_DECK"
    UNKNOWN_TYPE = "UNKNOWN_TYPE"
    STALE_ACTION = "STALE_ACTION"
    NOT_YOUR_PRIORITY = "NOT_YOUR_PRIORITY"
    ILLEGAL_ACTION = "ILLEGAL_ACTION"
    ILLEGAL_TARGET = "ILLEGAL_TARGET"
    TRIGGER_ORDER_INVALID = "TRIGGER_ORDER_INVALID"
    TRIGGER_CHOICE_INVALID = "TRIGGER_CHOICE_INVALID"
    INSUFFICIENT_MANA = "INSUFFICIENT_MANA"
    WRONG_PHASE = "WRONG_PHASE"
    DUPLICATE_ID = "DUPLICATE_ID"

# Global variables
DEFAULT_PORT = 4444
STARTING_LIFE = 20
#MAX_HAND_SIZE =
MAX_DECK_SIZE = 50
MIN_DECK_SIZE = 1
#DEFAULT_TIME_LIMIT =
#PING_INTERVAL =
#PING_TIMEOUT =